# Generated by Django 3.0.4 on 2020-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_num',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
