# Generated by Django 3.0.5 on 2020-06-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200420_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
