# Generated by Django 3.0.4 on 2020-03-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200311_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_num',
            field=models.CharField(max_length=9),
        ),
    ]
