# Generated by Django 3.0.5 on 2020-06-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200606_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Day'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Section'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Timeslot'),
        ),
    ]
