# Generated by Django 3.0.4 on 2020-03-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200310_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'preference list', 'verbose_name_plural': 'preference lists'},
        ),
        migrations.RemoveField(
            model_name='preference',
            name='name',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='value',
        ),
        migrations.AddField(
            model_name='preference',
            name='break_length',
            field=models.TimeField(null=True, verbose_name='break length'),
        ),
        migrations.AddField(
            model_name='preference',
            name='earliest_class_time',
            field=models.TimeField(null=True, verbose_name='earliest class time'),
        ),
        migrations.AddField(
            model_name='preference',
            name='latest_class_time',
            field=models.TimeField(null=True, verbose_name='latest class time'),
        ),
        migrations.AddField(
            model_name='preference',
            name='max_courses',
            field=models.IntegerField(null=True, verbose_name='max courses per day'),
        ),
        migrations.AddField(
            model_name='preference',
            name='min_courses',
            field=models.IntegerField(null=True, verbose_name='min courses per day'),
        ),
    ]
