# Generated by Django 3.0.4 on 2020-03-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_code',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
