# Generated by Django 3.0.4 on 2020-03-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_day_day_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day_code',
        ),
    ]
