# Generated by Django 3.0.4 on 2020-03-29 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_day_day_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowchart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=3)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Degree')),
            ],
            options={
                'verbose_name': 'flowchart',
                'verbose_name_plural': 'flowcharts',
            },
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'building', 'verbose_name_plural': 'buildings'},
        ),
        migrations.AlterModelOptions(
            name='courseoffering',
            options={'verbose_name': 'course offering', 'verbose_name_plural': 'course offerings'},
        ),
        migrations.AlterModelOptions(
            name='coursepriority',
            options={'verbose_name': 'course priority', 'verbose_name_plural': 'course priorities'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'day', 'verbose_name_plural': 'days'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'faculty member', 'verbose_name_plural': 'faculty members'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'schedule', 'verbose_name_plural': 'schedules'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'timeslot', 'verbose_name_plural': 'timeslots'},
        ),
        migrations.AddField(
            model_name='building',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(related_name='_course_prerequisites_+', to='api.Course'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursepriority',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='day',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='section',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FlowchartTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('flowchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Flowchart')),
            ],
            options={
                'verbose_name': 'flowchart term',
                'verbose_name_plural': 'flowchart terms',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='flowchart_terms',
            field=models.ManyToManyField(to='api.FlowchartTerm'),
        ),
    ]
