# Generated by Django 3.0.4 on 2020-03-31 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200329_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='course_priority',
        ),
        migrations.AddField(
            model_name='coursepriority',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
