# Generated by Django 3.0.5 on 2020-04-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200331_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='last_name',
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
