# Generated by Django 3.0.4 on 2020-03-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200312_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highprioritycourselist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lowprioritycourselist',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='highCourses',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.HighPriorityCourseList'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lowCourses',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.LowPriorityCourseList'),
            preserve_default=False,
        ),
    ]
