# Generated by Django 3.0.5 on 2020-04-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_courseoffering_classnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='end_AY',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='start_AY',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='term',
        ),
        migrations.AlterField(
            model_name='building',
            name='bldg_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.College'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Faculty'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Room'),
        ),
        migrations.AlterField(
            model_name='day',
            name='day_code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='day_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
