# Generated by Django 3.0.5 on 2020-04-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200402_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='break_length',
            field=models.IntegerField(null=True, verbose_name='break length'),
        ),
    ]
