# Generated by Django 3.0.4 on 2020-03-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200312_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='highCourses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.HighPriorityCourseList'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lowCourses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.LowPriorityCourseList'),
        ),
    ]
