# Generated by Django 3.0.4 on 2020-03-12 17:53

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200312_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='highCourses',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.HighPriorityCourseList'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lowCourses',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.LowPriorityCourseList'),
        ),
    ]
