# Generated by Django 3.0.4 on 2020-03-13 02:59

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200312_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bldg_name', models.CharField(max_length=100)),
                ('bldg_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='highCourses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lowCourses',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('room_capacity', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Building')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliest_class_time', models.TimeField(null=True, verbose_name='earliest class time')),
                ('latest_class_time', models.TimeField(null=True, verbose_name='latest class time')),
                ('break_length', models.TimeField(null=True, verbose_name='break length')),
                ('min_courses', models.IntegerField(null=True, verbose_name='min courses per day')),
                ('max_courses', models.IntegerField(null=True, verbose_name='max courses per day')),
                ('highCourses', annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.HighPriorityCourseList')),
                ('lowCourses', annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.LowPriorityCourseList')),
                ('preferred_buildings', models.ManyToManyField(null=True, to='api.Building')),
                ('preferred_faculty', models.ManyToManyField(null=True, to='api.Faculty')),
                ('preferred_sections', models.ManyToManyField(null=True, to='api.Section')),
            ],
            options={
                'verbose_name': 'preference_list',
                'verbose_name_plural': 'preference_lists',
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('start_AY', models.IntegerField()),
                ('end_AY', models.IntegerField()),
                ('current_enrolled', models.IntegerField()),
                ('max_enrolled', models.IntegerField()),
                ('status', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Day')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Section')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='PreferenceList',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PreferenceList'),
        ),
    ]
