# Generated by Django 3.0.5 on 2020-04-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_schedule_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='flowchart_terms',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='flowchartterm',
            name='flowchart',
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite_to',
            field=models.ManyToManyField(null=True, to='api.Course'),
        ),
        migrations.AddField(
            model_name='flowchartterm',
            name='batch',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowchartterm',
            name='courses',
            field=models.ManyToManyField(to='api.Course'),
        ),
        migrations.AddField(
            model_name='flowchartterm',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Degree'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Flowchart',
        ),
    ]
