# Generated by Django 3.0.4 on 2020-03-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200313_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencelist',
            name='preferred_days',
            field=models.ManyToManyField(to='api.Day'),
        ),
        migrations.AlterField(
            model_name='preferencelist',
            name='preferred_buildings',
            field=models.ManyToManyField(to='api.Building'),
        ),
        migrations.AlterField(
            model_name='preferencelist',
            name='preferred_faculty',
            field=models.ManyToManyField(to='api.Faculty'),
        ),
        migrations.AlterField(
            model_name='preferencelist',
            name='preferred_sections',
            field=models.ManyToManyField(to='api.Section'),
        ),
    ]
