# Generated by Django 3.0.5 on 2020-04-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200410_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_num',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
