# Generated by Django 3.0.4 on 2020-03-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200313_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseOfferings', models.ManyToManyField(to='api.CourseOffering')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='schedules',
            field=models.ManyToManyField(to='api.Schedule'),
        ),
    ]
