# Generated by Django 3.0.4 on 2020-03-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200322_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
