# Generated by Django 3.0.4 on 2020-03-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200322_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='degree_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
