# Generated by Django 3.0.4 on 2020-03-22 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200322_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.College'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Degree'),
            preserve_default=False,
        ),
    ]
