# Generated by Django 3.0.3 on 2020-02-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archerone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliest_class_time', models.TimeField(verbose_name='earliest class time')),
                ('latest_class_time', models.TimeField(verbose_name='latest class time')),
                ('break_length', models.TimeField(verbose_name='break length')),
                ('min_courses', models.IntegerField(verbose_name='min courses per day')),
                ('max_courses', models.IntegerField(verbose_name='max courses per day')),
            ],
            options={
                'verbose_name': 'preference list',
                'verbose_name_plural': 'preference lists',
            },
        ),
    ]
