# Generated by Django 3.0.3 on 2020-02-25 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archerone', '0002_preferencelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='archerone.PreferenceList'),
        ),
    ]
