# Generated by Django 3.0.3 on 2020-02-25 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archerone', '0003_user_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencelist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferences',
        ),
        migrations.AddField(
            model_name='preferencelist',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
