# Generated by Django 3.0.3 on 2020-02-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archerone', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='', max_length=100, verbose_name='college'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(default='', max_length=100, verbose_name='course'),
            preserve_default=False,
        ),
    ]
