# Generated by Django 3.0.3 on 2020-02-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archerone', '0004_auto_20200225_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencelist',
            name='break_length',
            field=models.TimeField(null=True, verbose_name='break length'),
        ),
        migrations.AlterField(
            model_name='preferencelist',
            name='earliest_class_time',
            field=models.TimeField(null=True, verbose_name='earliest class time'),
        ),
        migrations.AlterField(
            model_name='preferencelist',
            name='latest_class_time',
            field=models.TimeField(null=True, verbose_name='latest class time'),
        ),
        migrations.AlterField(
            model_name='preferencelist',
            name='max_courses',
            field=models.IntegerField(null=True, verbose_name='max courses per day'),
        ),
        migrations.AlterField(
            model_name='preferencelist',
            name='min_courses',
            field=models.IntegerField(null=True, verbose_name='min courses per day'),
        ),
    ]
